### ISSUE TITLE
QA: Available models

### ISSUE THREAD

**Issue by rmalav15** [facebookresearch/SpanBERT#11]
Hi,

Thank you for releasing the code. I want to use SpanBERT QA model for inference in my project. But I dont have resources to finetune it. In README, you have put

> If you are interested in using our fine-tuned models for downstream tasks (QA, coreference, relation extraction) directly, we also provide the following models:

Then there is no links for downloading. Please let me know if I am missing something. Can you please provide me a link to download pretrained Squad QA model?

Thanks,
Ram

**Comment by mandarjoshi90** [comment]
Hi. We'll make the models available soon (busy with some deadlines, sorry.)

**Comment by mandarjoshi90** [comment]
Hi Ramavtar,
The finetuned models can be downloaded from here. Replace task with one of {squad1, squad2, tacred}
http://dl.fbaipublicfiles.com/fairseq/models/spanbert_<task>.tar.gz

For coref models, please check this repository
https://github.com/mandarjoshi90/coref

I will update the README soon (need to prepare PRs). Please let me know if you face any access issues.

**Comment by rmalav15** [comment]
Thank You.
