### ISSUE TITLE
Weights of BertForQuestionAnswering not initialized from pretrained model?

### ISSUE THREAD

**Issue by luke4u** [facebookresearch/SpanBERT#20]
Hey Guys, 

I am trying to retrain on SQUAD 2.0 on google colab. Got a message below:

10/17/2019 15:12:24 - INFO - pytorch_pretrained_bert.modeling - Weights of BertForQuestionAnswering not initialized from pretrained model: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'qa_outputs.weight', 'qa_outputs.bias']
10/17/2019 15:12:24 - INFO - __main__ - Start epoch #0 (lr = 2e-05)...
^C

To reproduce my above:

!python ./code/run_squad.py \
  --do_train \
  --do_eval \
  --model spanbert-large-cased \
  --train_file train-v2.0.json \
  --dev_file dev-v2.0.json \
  --train_batch_size 32 \
  --eval_batch_size 32  \
  --learning_rate 2e-5 \
  --num_train_epochs 4 \
  --max_seq_length 512 \
  --doc_stride 128 \
  --eval_metric best_f1 \
  --output_dir ./squad2_output \
  --version_2_with_negative \

I checked modelling.py, message is from line 647. It seems there are missing_keys about TF weights? Can anyone give an instruction? 

Thanks. 
Luke

**Comment by mandarjoshi90** [comment]
Not sure I understand. If you're finetuning on SQuAD, you won't have those keys in the checkpoint which is why they're not initialized. But the finetuning should still proceed. Is it throwing an error?
