### ISSUE TITLE
coref part is a mess 

### ISSUE THREAD

**Issue by juliahane** [facebookresearch/SpanBERT#21]
Hi
While I really appreciate the code for all the experiments are very clean, the coref experiment code is just a mess, there is a a lot of files with no structure, literally nothing just pushed in a repo, please please spend some time, come back to those code, write a clean, structured code, this is a good work and really a pity that part of experiments is very hard to reproduce the results, and is written in a very messy way, thanks

**Comment by mandarjoshi90** [comment]
Most of the code has been carried over from previous work, and there's not a lot of fresh code we wrote apart from the optimization. Rewriting code is not a top priority for us. 

And please use the coref repo for these questions.
