### ISSUE TITLE
training model with own data

### ISSUE THREAD

**Issue by platinum736** [facebookresearch/SpanBERT#27]
Hi, I am looking to train this model on my own data which have different relation classes. 
Currently I am a bit confused with the data format you have used for training and evaluating the result. I am able to run this code but have doubt regarding different terminologies used in code and if I have formatted my data correctly according to them.
**Can you please share an example dataset file having 5-10 records.** I would like to run on this datset and be sure.

**Comment by mandarjoshi90** [comment]
Not sure I understand. If this is about relation extraction, we used the TACRED dataset. 
https://nlp.stanford.edu/projects/tacred/

**Comment by platinum736** [comment]
Hi @mandarjoshi90 , 
Thanks for your reply. I understand that you have used TRACRED, but my question was about how you formatted that data. I mean how do you represent entities and data together to train your model.
for eg: surrounding the entities  with an special entity specific embedding  or something else

**Comment by danqi** [comment]
@platinum736 Please see the implementation here: https://github.com/facebookresearch/SpanBERT/blob/master/code/run_tacred.py#L116-L221

We implemented four different feature modes: text, ner, ner_text, text_ner. 
And we only used "ner" mode at the end for the TACRED results (use NER tags to replace entity text).

Hope this helps.
