### ISSUE TITLE
Is it possible to release the code for pretraining data creation?

### ISSUE THREAD

**Issue by l11x0m7** [facebookresearch/SpanBERT#3]
Hi, I wonder if it's possible to release your pretraining data creation code described in your paper?

**Comment by omerlevy** [comment]
Unfortunately, we cannot release our pre-training data due to licensing issues.

**Comment by houliangxue** [comment]
> Hi, I wonder if it's possible to release your pretraining data creation code described in your paper?
Hi, have you got the code or did it yourself ? if possible ,can you share it with me?

**Comment by houliangxue** [comment]
> Hi, I wonder if it's possible to release your pretraining data creation code described in your paper?

Hi, have you got the code or did it yourself ? if possible ,can you share it with me? thanks.
