### ISSUE TITLE
800 tokens

### ISSUE THREAD

**Issue by NonaryR** [facebookresearch/SpanBERT#32]
Hello! Can you please explain why you choose a limit in 800 tokens? And how you tokenize text - you have only 800 tokens of the entire dataset, or you processed each record with a new tokenizer instance and built fresh vocab?

**Comment by mandarjoshi90** [comment]
I take it that you're referring to MRQA? If so, that was not our decision. That's how the organizers preprocessed their data.

Each QA *passage* has 800 tokens of context. The vocabulary does not depend on the downstream task; we used the BERT cased vocabulary.
