### ISSUE TITLE
Translate into tensorflow ckpt model

### ISSUE THREAD

**Issue by mujizi** [facebookresearch/SpanBERT#35]
hello author:
i want to use spanbert for my task, but my task code build with tensorflow, spanbert is a pytorch.bin file. How to make change to get ckpt tensorflow model. :)

best wish.

**Comment by mujizi** [comment]
I want get ckpt model.

**Comment by mandarjoshi90** [comment]
This might be useful -- https://github.com/mandarjoshi90/coref/blob/master/pytorch_to_tf.py#L38

**Comment by mujizi** [comment]
thanks for your reply，I have solved this problem
