### ISSUE TITLE
Prepare training data

### ISSUE THREAD

**Issue by saravananpsg** [facebookresearch/SpanBERT#37]
I tried to train using **_run_mrqa.py_** with the json files (by changing the read files codes). However, I am unable to proceed further. Any help would be appreciated. Please share the preparation for HotpotQA dataset using SpanBERT.

**Comment by mandarjoshi90** [comment]
Could you please include the command you used and the error messages?

**Comment by saravananpsg** [comment]
Hi @mandarjoshi90,
I used the following command to run the script and initially I got an TypeError as the format of the paragragh text [list of list] is different from other datasets. 

_python code/run_mrqa.py \
  --do_train \
  --do_eval \
  --model spanbert-base-cased \
  --train_file hotpot_train_v1.json \
  --dev_file hotpot_dev_distractor_v1.json \
  --train_batch_size 32 \
  --eval_batch_size 32 \
  --learning_rate 2e-5 \
  --num_train_epochs 4 \
  --max_seq_length 512 \
  --doc_stride 128 \
  --eval_per_epoch 5 \
  --output_dir out_qa_dir \
  --fp16_

**Error Log**

_File "code/run_mrqa.py", line 112, in is_whitespace
    if c == " " or c == "\t" or c == "\r" or c == "\n" or ord(c) == 0x202F:
TypeError: ord() expected string of length 1, but list found_

**Comment by mandarjoshi90** [comment]
Is this file actually in the same format as the MRQA datasets?

**Comment by saravananpsg** [comment]
@mandarjoshi90 No. I understand now!
