### ISSUE TITLE
Apex ModuleNotFoundError: 'fused_adam_cuda'

### ISSUE THREAD

**Issue by kaniblu** [facebookresearch/SpanBERT#43]
I am using the same python packages as specified in `requirements.txt` and README (apex@4a8c4ac).
Python version 3.6.10
I get the following error after running the SQuAD 2.0 command about 10 minutes in.

```
05/06/2020 08:17:34 - INFO - pytorch_pretrained_bert.modeling - Weights of BertForQuestionAnswering not initialized from pretrained model: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'qa_outputs.weight', 'qa_outputs.bias']
Traceback (most recent call last):
  File "code/run_squad.py", line 1138, in <module>
    main(args)
  File "code/run_squad.py", line 947, in main
    max_grad_norm=1.0)
  File "/home/user/.conda3/envs/spanbert/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/optimizers/fused_adam.py", line 40, in __init__
  File "/home/user/.conda3/envs/spanbert/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_adam_cuda'
```

**Comment by mandarjoshi90** [comment]
Possibly an Apex issue? Did you try the version in the README?

**Comment by kaniblu** [comment]
Like I mentioned, I am using the one in the README.

**Comment by mandarjoshi90** [comment]
Apologies. I missed that. Not sure what's wrong then. All the related github threads seem to be coming from the Apex repo, so it does seem to be the source.

**Comment by kaniblu** [comment]
Turns out that `apex` wasn't installed correctly. I installed by `python setup.py install` and not following the instruction on apex's README file. Thanks anyways!

**Comment by ouening** [comment]
> Turns out that `apex` wasn't installed correctly. I installed by `python setup.py install` and not following the instruction on apex's README file. Thanks anyways!

I met the same error, and I installed the `apex` from the latest source, that does't work for me. Which version of apex do you use?

**Comment by varadhbhatnagar** [comment]
@kaniblu  Can you elaborate a bit on how you solved this issue? I am having the same problem.

**Comment by kaniblu** [comment]
@varadhbhatnagar You should install `apex` with the recommended command in README and not by simply running `pip install setup.py`. Especially if you are installing it with the CUDA capabilities.

**Comment by vincentlux** [comment]
For those who still met the issue, this way of installation works for me: https://github.com/NVIDIA/apex/issues/86#issuecomment-455620478

**Comment by xuuuluuu** [comment]
@kaniblu @vincentlux May I know the version of Pytorch, CUDA you are using? 

With the recommended command in README: pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./ 

I am still not able to install the apex. Below is the main error:

/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension

...

Given no hashes to check 145 links for project 'pip': discarding no candidates.

**Comment by tyistyler** [comment]
@kaniblu
excuse me , could you tell me how to install apex@4a8c4ac
I just use
--!git clone https://github.com/NVIDIA/apex
--cd apex
--!pip install -v --no-cache-dir --global-option="--cpp_ext" '
and modify the 'from apex.optimizers import FusedAdam' to 'from apex.contrib.optimizers import FusedAdam'
but I get the same question with you
thanx~

**Comment by xuuuluuu** [comment]
@tyistyler I believe you can try "git checkout 4a8c4ac" before pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

p.s. I just installed it when I downgrade my pip to 18.0

**Comment by tyistyler** [comment]
Thanks a lot!!

















At 2020-08-16 16:22:08, "xuuuluuu" <notifications@github.com> wrote:

@tyistyler I believe you can try "git checkout 4a8c4ac" before pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

p.s. I just installed it when I downgrade my pip to 18.0

**Comment by phosseini** [comment]
> @tyistyler I believe you can try "git checkout 4a8c4ac" before pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
> 
> p.s. I just installed it when I downgrade my pip to 18.0

Thanks for sharing this, I still have some trouble installing the apex. The one thing I don't get is how to install that specific [commit of apex](NVIDIA/apex@4a8c4ac) that is mentioned in the readme. Is this `git checkout 4a8c4ac` the exact command you used for that since it does not look like a valid command?
