### ISSUE TITLE
 Miss SBO head parameters

### ISSUE THREAD

**Issue by zyccyz** [facebookresearch/SpanBERT#44]
Hi, I‘m doing a research about relation extraction. I think SpanBert is perfect for my method, but when I used MLM head or SBO head for transfer learning, I found that the pretrained model loses some parameters. So I want to know if it is possible to get  the complete PTM parameters. Thanks so much!

**Comment by mandarjoshi90** [comment]
The model file is here:
https://dl.fbaipublicfiles.com/fairseq/models/spanbert_large_with_head.tar.gz

**Comment by yimmon** [comment]
@mandarjoshi90 Could you provide us the base model with head parameters? Training large model is hard for us, so I think the base model is more useful for us. Thank you very much.
