### ISSUE TITLE
Are the pre-trained models on this repository "Multilingual" versions of SpanBERT or only English? if not, is there any multilingual version available to download?

### ISSUE THREAD

**Issue by mahdiabdollahpour** [facebookresearch/SpanBERT#47]
Are the pre-trained models on this repository "Multilingual" versions of SpanBERT or only English? if not, is there any multilingual version available?

**Comment by mandarjoshi90** [comment]
Sorry, we don't have multilingual SpanBERT models. You might want to check out XLM-R here.

https://github.com/pytorch/fairseq/tree/master/examples/xlmr
