### ISSUE TITLE
Migrating to HuggingFace's Transformers

### ISSUE THREAD

**Issue by phosseini** [facebookresearch/SpanBERT#48]
I'm trying to convert the `run_tacred.ty` to a Huggingface's Transformers compatible version. I load the SpanBERT fine-tuned model for `tacred` and tokenizer using the following code:

```
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("SpanBERT/spanbert-base-cased")
model = AutoModel.from_pretrained("SpanBERT/spanbert-base-cased")
```

But at the evaluation time, when I get to the following section:

```
with torch.no_grad():
     logits = model(input_ids, segment_ids, input_mask)
loss_fct = CrossEntropyLoss()
tmp_eval_loss = loss_fct(logits.view(-1, num_labels), label_ids.view(-1))
```

I get the following error:

`AttributeError: 'tuple' object has no attribute 'view'`

which means the output of the model, `logits`, is not a torch tensor. I'm trying to figure out what the correct size of `logits` is for the `loss_fct` function. `logits` has two elements where each of them is `torch.Size([32, 128, 1024])` where 32 is the batch size. `label_ids` here is also `torch.Size([32])`.

Based on the dimensions, I tried the following for the `loss_fct` based on the acceptable input dimension for `loss_fct`:

`tmp_eval_loss = loss_fct(logits[0].view(list(input_ids.size())[0], -1), label_ids.view(-1))`

which even though passes the computing loss function step, it throws an error in `compute_f1` since we'll have the `preds` of size `(n, 1024)` where `n` is the total number of data points we are evaluating while the `labels`'s size is `n`.

I wonder how should I set the dimensions?

**Comment by jiajinghu19** [comment]
When I tried to load it using huggingface's AutoModel in your way, it gave me the same model as Bert Model. Are you able to get different weights from Bert?

**Comment by mandarjoshi90** [comment]
Hi Pedram. It seems like this is being caused by a change in torch/transformers API. Perhaps it might help to run the original code and figure out the dimensions?

**Comment by phosseini** [comment]
> Hi Pedram. It seems like this is being caused by a change in torch/transformers API. Perhaps it might help to run the original code and figure out the dimensions?

Thanks for your response. Even running the original code results in the following error:

```

Traceback (most recent call last):
  File "code/run_tacred.py", line 571, in <module>
    main(args)
  File "code/run_tacred.py", line 512, in main
    model = BertForSequenceClassification.from_pretrained(args.output_dir, num_labels=num_labels)
  File "/Users/phosseini/PycharmProjects/SpanBERT/code/pytorch_pretrained_bert/modeling.py", line 654, in from_pretrained
    model.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BertForSequenceClassification:
	size mismatch for classifier.weight: copying a param with shape torch.Size([42, 1024]) from checkpoint, the shape in current model is torch.Size([3, 1024]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([42]) from checkpoint, the shape in current model is torch.Size([3]).

```

This is the script I'm running:

```
import os

os.system("python code/run_tacred.py \
  --do_eval \
  --data_dir \"./data/tacred/\" \
  --model spanbert-base-cased \
  --train_batch_size 32 \
  --eval_batch_size 32 \
  --learning_rate 2e-5 \
  --num_train_epochs 5 \
  --max_seq_length 128 \
  --output_dir \"./models/tacred/\"")

```

I just simply created a dev and test set with 110 samples each in TACRED format and I'm running the original code in evaluation mode just to see if the code is running, but I still get the error. Any thoughts?

**Comment by phosseini** [comment]
I could resolve the issue I just mentioned by adding `model = nn.DataParallel(model)` before `load(model, prefix=start_prefix)` in the `modeling.py` class

**Comment by phosseini** [comment]
I finally got a chance to write a transformers compatible version of `run_tacred.py`. You can find it here: [https://github.com/phosseini/SpanBERT/blob/main/code/run_crest.py](https://github.com/phosseini/SpanBERT/blob/main/code/run_crest.py) 

I haven't tested it with `fp16` yet. Since I have made other changes to my forked repository, I am not able to create a pull request for now, but meanwhile, I thought someone might find this code helpful.
