### ISSUE TITLE
How do I load the pretrained model?

### ISSUE THREAD

**Issue by jiajinghu19** [facebookresearch/SpanBERT#49]
I downloaded the ```spanbert_hf_base.tar``` file and when I load it ```torch.load(spanbert_hf_base.tar)```, it gave me the error ```KeyError: "filename 'storages' not found"```. How do I properly load the pretrained model? Thanks

**Comment by mandarjoshi90** [comment]
Not quite sure what the setup is but `torch.load` is going to need a checkpoint. I think you'll have to untar the file and try with the checkpoint file.

**Comment by jiajinghu19** [comment]
When I untar it, there are only two files, one is a config.json file, the other one is pytorch_model.bin. I used ```torch.load('pytorch_model.bin')``` but it gave me a ```collections.OrderedDict``` object, instead of a model object. Did I load it in the wrong way? Thanks

**Comment by mandarjoshi90** [comment]
That's expected. Perhaps, this might be useful:
[https://github.com/facebookresearch/SpanBERT/blob/master/code/pytorch_pretrained_bert/modeling.py#L530](https://github.com/facebookresearch/SpanBERT/blob/master/code/pytorch_pretrained_bert/modeling.py#L530)

**Comment by jiajinghu19** [comment]
Thank you. It gave me an empty ```BertPreTrainedModel()``` with this method
