### ISSUE TITLE
[QUESTION] What type of relation extraction is SpanBERT suited for?

### ISSUE THREAD

**Issue by phosseini** [facebookresearch/SpanBERT#50]
SpanBERT is fine-tuned and tested on TACRED where relation spans are mostly subjects and objects in a sentence with usually not more than 1-2 words in each span. Also, based on Figure 2 in the paper, the majority of the spans for pre-training SpanBERT are between 1-3 words in length. We have Relation Extraction tasks though, in which spans may be an event or even a complete sentence. I wonder if you think SpanBERT would be a good fit for such relation extraction tasks? One example, in the following document:

> Kanner's reuse of "autism" led to decades of confused terminology like "infantile schizophrenia", and child psychiatry's focus on maternal deprivation led to misconceptions of autism as an infant's response to "refrigerator mothers".

There's a causal relation between `(Kanner's reuse of "autism", decades of confused terminology like "infantile schizophrenia")` where spans are longer than what we usually see in datasets such as TACRED (some might argue that these spans can be pruned and shortened, but my point is if overall SpanBERT is suitable for longer spans in a relation extraction task)

**Comment by mandarjoshi90** [comment]
Interesting question! It is admittedly hard to say for certain what will happen in your case. But, I'd like to think--after controlling for other pretraining details--SpanBERT is still more used to longer spans than comparable models. If and when you get results, I'd love to hear about them. Thanks!

**Comment by phosseini** [comment]
> Interesting question! It is admittedly hard to say for certain what will happen in your case. But, I'd like to think--after controlling for other pretraining details--SpanBERT is still more used to longer spans than comparable models. If and when you get results, I'd love to hear about them. Thanks!

I'm about to test the model, just a quick question: a data point in TACRED has the following format:

<img width="245" alt="Screen Shot 2020-07-19 at 9 24 14 PM" src="https://user-images.githubusercontent.com/25105263/87891064-c0b62b00-ca06-11ea-811c-f70c737ed974.png">

Considering the fact that for longer spans, it may not make much sense to have NER tags, should I provide the NER tags when I'm converting my inputs to TACRED format? Or is it just enough to have spans and their start and end indices in the `token` list? I'm writing a new `run_*.py` class for my task, but I'm basically trying to figure out which elements in a record are essential to be fed to SpanBERT for the type of relation extraction I described earlier.

**Comment by mandarjoshi90** [comment]
I think it should be ok to skip the tags for your task.
