### ISSUE TITLE
model load error

### ISSUE THREAD

**Issue by addf400** [facebookresearch/SpanBERT#7]
https://github.com/facebookresearch/SpanBERT/blob/master/code/pytorch_pretrained_bert/modeling.py#L616

        for key in state_dict.keys():
            # new_key = key[8:] if key.startswith("decoder.") else key
            if 'gamma' in new_key:
                new_key = new_key.replace('gamma', 'weight')
            if 'beta' in new_key:
                new_key = new_key.replace('beta', 'bias')
            if key != new_key:
                old_keys.append(key)
                new_keys.append(new_key)

I check the parameters, there is no parameters for decoder (prediction layer), these code should be removed.

**Comment by omerlevy** [comment]
Sorry, I don't understand. Did you either (1) get an error when loading the model, or (2) just making a comment that this code is unnecessary?

If the case is (1), can you please share the command you ran and the error details?

As for (2), this is to support loading the original fairseq-trained models. We might remove or modify this in the future.

**Comment by addf400** [comment]
> Sorry, I don't understand. Did you either (1) get an error when loading the model, or (2) just making a comment that this code is unnecessary?
> 
> If the case is (1), can you please share the command you ran and the error details?
> 
> As for (2), this is to support loading the original fairseq-trained models. We might remove or modify this in the future.

It is (1).
Comment the code "new_key = key[8:] if key.startswith("decoder.") else key" will not assign "new_key", it will cause next line error.

**Comment by omerlevy** [comment]
Thanks, fixed.
