### ISSUE TITLE
Could you provide uncased SpanBert?

### ISSUE THREAD

**Issue by WenzhengZhang** [facebookresearch/SpanBERT#73]
Hi, could you provide the uncased version of SpanBert? Thanks a lot!

**Comment by mandarjoshi90** [comment]
Sorry, we did not train the uncased version for this project.

**Comment by WenzhengZhang** [comment]
Thanks for your reply! Do you have any plan to train the uncased version?

**Comment by mandarjoshi90** [comment]
Nope, we're no longer actively working on this. Thanks!
