### ISSUE TITLE
continue pretraining

### ISSUE THREAD

**Issue by houliangxue** [facebookresearch/SpanBERT#79]
Hi，when I tried  load your pretrained model(SpanBERT base & cased) and continue pretraining，I got the erro
Exception:“Cannot load model parameters from checkpoint, please ensure that the architectures match”
so，how can I load your （SpanBERT base & cased）correctly，please

**Comment by phosseini** [comment]
@houliangxue I wonder if you could run the continued pretraining successfully? If yes, can you let me know how you loaded the pretrained model? I have the `model.pt` which is the pretrained checkpoint, but not sure how to properly load it before running the `train.py` for continued pretraining.
