### ISSUE TITLE
unexpected keyword argument `max_grad_norm` in `run_squad.py`

### ISSUE THREAD

**Issue by Dobatymo** [facebookresearch/SpanBERT#8]
Training SQuAD 2.0 with the command given in README.md raises following error

```
Traceback (most recent call last):
  File "code/run_squad.py", line 1138, in <module>
    main(args)
  File "code/run_squad.py", line 947, in main
    max_grad_norm=1.0)
TypeError: __init__() got an unexpected keyword argument 'max_grad_norm'
```

According to https://nvidia.github.io/apex/optimizers.html `FusedAdam` doesn't take a `max_grad_norm` argument.

**Comment by antonyscerri** [comment]
You need to checkout an earlier commit of Apex - https://github.com/NVIDIA/apex/commit/4a8c4ac088b6f84a10569ee89db3a938b48922b4

That's the last commit which matches the call from SpanBERT. I've been able to build that one and get SpanBERT running, hopefully that will get you going.

**Comment by Dobatymo** [comment]
Thanks for your help. I will try that.

**Comment by non-swimmer** [comment]
Hi, how did you solve this problem? just delete the argument max_grad_norm? could you please show more details?

**Comment by non-swimmer** [comment]
> Thanks for your help. I will try that.
> Update: Everything seems to work using that commit. Maybe that should be added to the readme.

Hi, how did you solve this problem? just delete the argument max_grad_norm? could you please show more details?

**Comment by antonyscerri** [comment]
Hi you need to checkout the specific commit i mentioned above for Apex, rebuild and install Apex and then this project should work fine as-is.
